## Install Wordpress Plugin [POST /api/plugins/install]
Install Wordpress plugin from repository.

+ Request (application/json)

        {
            "Plugin":"wpinstaller"
        }

+ Response 204 (text/plain)

## Install Wordpress to domain dir as #User [POST /api/webdomains/set]
Add wordpress_install_dir to install WP on domain's directory.

+ Request (application/json)

         {  
            "Name":"$TESTING_DOMAIN",
            "Active":true,
            "Alias":"www.$TESTING_DOMAIN site.$TESTING_DOMAIN",
            "Ip":"$SERVER_IP",
            "IndexFile":"index.html index.php",
            "Encoding":"utf8",
            "Subdomains":true,
            "PHP":"fpm_nginx",
            "DNS":true,
            "SSL":false,
            "Analytics":true,

            "wordpress_install_dir":"wordpress"
        }

+ Response 204 (text/plain)

## Remove Wordpress Plugin [POST /api/plugins/del]
Remove Wordpress plugin from system.

+ Request (application/json)

        [ "wpinstaller" ]

+ Response 204 (text/plain)
