## Install PhpMyAdmin Plugin [POST /api/plugins/install]
Install PhpMyAdmin plugin from repository

+ Request (application/json)

        {
            "Plugin":"pmainstaller"
        }

+ Response 204 (text/plain)

## Add pmainstall to domain as #User [POST /api/webdomains/set]
Add pmainstall true to install phpmyadmin on domain.

+ Request (application/json)

         {
            "Name":"$TESTING_DOMAIN",
            "Active":true,
            "Alias":"www.$TESTING_DOMAIN site.$TESTING_DOMAIN",
            "Ip":"$SERVER_IP",
            "IndexFile":"index.html index.php",
            "Encoding":"utf8",
            "Subdomains":true,
            "PHP":"fpm_nginx",
            "DNS":true,
            "SSL":false,
            "Analytics":true,

            "pmainstall":true
        }

+ Response 204 (text/plain)

## !Hook test installation [HEAD /@hook]

Test plugin installation by bot.

+ Response 299

## Remove PhpMyAdmin Plugin [POST /api/plugins/del]
Remove PhpMyAdmin plugin from system

+ Request (application/json)

        [ "pmainstaller" ]

+ Response 204 (text/plain)
