## Search Ruby Gems [POST /api/ruby/search]

Search for ruby gems.

+ Request (application/json)

        ["radar-mysql"]

+ Response 200 (application/json)

        [
            {
                "Name":        "Package",
                "Version":     "1.0.9",
                "Description": "sql driver"
            }
        ]

## Install Gem package [POST /api/ruby/install]

Install Ruby gem package.

+ Request (application/json)

        ["zabbapi"]

+ Response 200 (application/json)

        [
            "Output"
        ]
        
## Install Gem package #Error [POST /api/ruby/install]

Install Ruby gem package with error.

+ Request (application/json)

        ["nosuchgem"]

+ Response

## List installed Ruby Gems packages [GET /api/ruby/list]

List all installed Ruby packages.

+ Response 200 (application/json)

        [
            {
                "Name":        "Package",
                "Version":     "1.0.9",
                "Description": "sql driver"
            }
        ]

## Update Ruby Gems [GET /api/ruby/update]

Updates Ruby gems packages and system gem package.

+ Request (application/json)

        ["google"]

+ Response 200 (application/json)

        [
            "Output"
        ]

## Remove Gem package [POST /api/ruby/remove]

Remove Ruby gem package.

+ Request (application/json)

        ["google"]

+ Response 200 (application/json)

        [
            "Output"
        ]

