## Create backup #User [GET /api/ubackup/create]

+ Response 204 (text/plain)

## Show #User messages [GET /api/messages/list]

+ Response 200 (application/json)

## Transfer backup to remote server [GET /api/shell/exec]

+ Request (application/json)
        {
            "Cmd":"ssh root@$BACKUP_SERVER_IP 'rm -dfr /tmp/backups/*; mkdir /tmp/backups;'; scp /home/backupUser/backups/*.tar.gz root@$BACKUP_SERVER_IP:/tmp/backups/latestBackup.tar.gz"
        }

+ Response 200 (application/json)
        {
                "Output":"CMD output"
        }
