## Add DKIM [/api/dkim/set]

Generates new DKIM key for domain and add it to EXIM and DNS record. If DKIM already exists it will be overwritten.

+ Attributes
	+ Domain (required, string) - Domain name to generate.

### Generate new DKIM [POST]

+ Request (application/json)
		{  
		   "Domain":"test.com"
		}

+ Response 204 (text/plain)

## Get DKIM keys [/api/dkim/get]

Getting public and private DKIM keys for domain in request.

+ Attributes
	+ Public (required, string) - Public DKIM key.
	+ Private (required, string) - Private DKIM key.

### Get DKIM key [POST]

+ Request (application/json)
		{  
		   "Domain":"test.com"
		}

+ Response 200 (application/json)
		{  
	      "Public":"public_key",
	      "Private":"private_key"
		}

## Remove DKIM key from domain [/api/dkim/del]

Remove DKIM keys from domain(s).

### Remove DKIM keys [POST]

+ Request (application/json)
		["test.com"]

+ Response 204 (text/plain)

### Remove non existent DKIM key [POST]

+ Request (application/json)
		["notExisting.com"]

+ Response 500 (application/json)
		{
		}