## Add or Edit Web domain [/api/webdomains/set]

Add new or edit web domain.

+ Attributes
  + Domain (required, string) - Web domain name.
  + Alias (required, string) - Domain aliases.
  + IP (required, string) - IP address to bind web domain.
  + IndexFile (required, string) - Index file.
  + Encoding (required, string) - Encoding for the files.
  + Subdomains (required, boolean) - Auto subdomains.
  + PHP (required, string) - PHP interpreter.
  + DNS (required, boolean) - Add domain to DNS server too.
  + SSL (required, boolean) - HTTPS support.
  + Analytics (required, boolean) - Domain analytics.

### Add new or edit web domain [POST]

+ Request (application/json)
    {  
       "Name":"testDomain.com",
       "Alias":"www.testDomain.com site.testDomain.com",
       "Ip":"$SERVER_IP",
       "IndexFile":"index.html",
       "Encoding":"utf8",
       "Subdomains":true,
       "PHP":"fpm_nginx",
       "DNS":true,
       "SSL":false,
       "Analytics":true,
       "Active":true
    }

+ Response 204 (text/plain)

## Toggle active web domains [/api/webdomains/toggle]

Activate or deactivate (if domain active) web domains in request.
Disabled domains will not be served from webserver.

### Toggle active web domains [POST]

+ Request (application/json)
    [  
       "testDomain.com"
    ]

+ Response 204 (text/plain)

### Toggle non existent web domain #Error [POST]

+ Request (application/json)
    [  
       "notExistingDomain.com"
    ]

+ Response

## List all web domains [/api/webdomains/list]

List all web domains of current user.

+ Attributes
  + Active (required, boolean) - Is domain active.
  + Apache (required, array) - Apache config parameters.
  + Nginx (required, array) - Nginx config parameters.

### List web domains [GET]

+ Response 200 (application/json)

      {  
        "testDomain.com":{  
            "Active":true,
            "Owner":"regular_User",
            "Alias":"www.testDomain.com site.testDomain.com",
            "Ip":"$SERVER_IP",
            "IndexFile":"index.html",
            "Encoding":"utf8",
            "Subdomains":true,
            "PHP":"fpm_nginx",
            "DNS":true,
            "SSL":false,
            "Analytics":true
        }
      }

## Remove web domains [/api/webdomains/del]

Remove web domains.

### Remove web domains [POST]

+ Request (application/json)
    [  
       "testDomain.com"
    ]

+ Response 204 (text/plain)

### Remove non existent web domain #Error [POST]

+ Request (application/json)
    [  
       "notExistingDomain.com"
    ]

+ Response
