## Data Structures

### DateInterval
+ From (required, string) - Date from show statistic in 2099.12.31 format.
+ To (required, string) - Date to show statistic in 2099.12.31 format.

### DomainStats
+ Date Interval
+ Domain (required, string) - For which domain show statistics for urls pathes.

### UrlStats
+ Date Interval
+ Url (required, string) - For which url show dates and count statistic.
