# Group URLs statistics
ServerPanel gather Domain and URL hits statistics at near realtime speed (save every minute) and store it for 30 days.
Administrator and Users can retrieve those statistics for all domains and by particular urls.
With ServerPanel there is no need to analyze large access logs files to retrieve web sitest statistic.
