# Group Domains statistics

ServerPanel gather Domain and URLs hits statistics at near realtime speed (minute or less) and store it for ***30 days*** by default.

`Administrator` and `Users` can retrieve those statistics for all domains and filter it by particular urls and date interval.

With ServerPanel there is no need to analyze large access logs files to retrieve web sitest statistic.
