# Group Domains statistics

ServerPanel gather ***Domains*** and ***URLs*** hits statistics directly from webserver and DNS.

There is no need to analyze large `access.log` files to retrieve web sites statistic. Its available at any time with minute delay.

> Statistics for websites stores at panel database for ***30 days*** period by default.

`Administrator` and `Users` can retrieve those statistics for all domains and filter it by particular urls and date interval.

![Domain statistics diagram](https://github.com/geeksteam/SHM-api-blueprint/raw/master/src/common/images/NgStat.svg "Domain Statistic diagram")
