## Get all domains statistics [GET /api/ngstat/get]

`Root` user (or Administrator) get count of hits for all domains at the server sorted by date interval.

As a response you'll get `Dates` objects with `Domain:hits` as a values.

+ Attributes (All stats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN":6
                }
            }

## Get all domains statistics by #User [GET /api/ngstat/get]

Get count of hits for current user domains by date interval.

+ Attributes (All stats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN":6
                }
            }

## Get domain statistics by #User [GET /api/ngstat/getdomain]

Get URLs with count of hits for Domain and date interval.

+ Attributes (Domains stats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD",
            "Domain":"$TESTING_DOMAIN"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN/url_one":1,
                    "$TESTING_DOMAIN/url_two":2,
                    "$TESTING_DOMAIN/url_three":3
                }
            }

## Get URL statistics by #User [GET /api/ngstat/geturl]

Get URL statistic by dates and hits count.

+ Attributes (URL stats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD",
            "Url":"$TESTING_DOMAIN/url_one"
        }

+ Response 200 (application/json)
            {
            }
