## All domains statistic [/api/ngstat/get]

`Root` user (or Administrator) get count of hits for all domains at the server sorted by date interval.

As a response you'll get `Dates` objects with `Domain:hits` as a values.


### Get stats [POST]

Root will get stats for all Domains.

+ Attributes (DateInterval)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN":6
                }
            }


### Get domains stats by #User [POST]

User will get stats only for his Domains.

+ Attributes (DateInterval)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN":6
                }
            }


## Statistic by URLs for Domain [/api/ngstat/getdomain]

Get URLs with count of hits for Domain and date interval.

As a response you'll get `Date` objects with `URL/path:hits` as value.


### Get URLs stats for Domain by #User [POST]

User can get stats for his Domains only.

+ Attributes (DomainStats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD",
            "Domain":"$TESTING_DOMAIN"
        }

+ Response 200 (application/json)
            {  
                "$DATE_YMD":{  
                    "$TESTING_DOMAIN/url_one":1,
                    "$TESTING_DOMAIN/url_two":2,
                    "$TESTING_DOMAIN/url_three":3
                }
            }


## URLs statistics by Date [/api/ngstat/geturl]

Get URL statistic by dates and hits count.

As a response you'll get `Date:hits` array.


### Get stats by Dates for URL path as #User [POST]

+ Attributes (UrlStats)

+ Request (application/json)
        {  
            "From":"$DATE_YMD",
            "To":"$DATE_YMD",
            "Url":"$TESTING_DOMAIN/url_one"
        }

+ Response 200 (application/json)
            {
            }
