## Get all domains statistics [GET /api/ngstat/get]
Getting count of views by url for all domains by date interval.

+ Request (application/json)
        {  
        "From":"01.09.2015",
        "To":"10.06.2016"
        }

+ Response 200 (application/json)
            {  
                "2015-09-09":{  
                    "domain1.com":324
                },
                "2015-09-10":{  
                    "domain1.com":34
                }
            }

## Get all domains statistics by #User [GET /api/ngstat/get]
Getting count of views by url for all user domains by date interval.

+ Request (application/json)
        {  
        "From":"01.09.2015",
        "To":"10.06.2016"
        }

+ Response 200 (application/json)
            {  
                "2015-09-09":{  
                    "domain1.com":324
                },
                "2015-09-10":{  
                    "domain1.com":34
                }
            }
