## Import dump to PgSQL database [POST /api/pgsql/db/import]

+ Request (application/json)

        {
                "Filepath": "/www/pgsql.sql",
                "Db": "DbImport"
        }

+ Response 204 (text/plain)
