## Export database [POST /api/pgsql/db/export]

Dump PgSQL databse and send it.

+ Attributes
  + Database (required, string) - Database name to dump.

+ Request (application/json)
        {  
       "Dbname":"DbExport"
    }

+ Response 200 (text/plain)
