# Group Remove Test environment
Remove test environment.

## Remove Databases test users [/api/mysql/users/del]

### Remove MySQL test user as #User [POST]

+ Request (application/json)
        {  
            "Username":"DBUser1"
        }

+ Response 204 (text/plain)

### Remove PgSQL test user as #User [POST]

+ Request (application/json)
        {  
            "Username":"DbTester"
        }

+ Response 204 (text/plain)

## Remove dirs for archive testing [/api/filemanager/del]

### Remove dirs for ZIP archive testing as Root [POST]

+ Request (application/json)
        [
            "/var/www/test_archives/zip"
        ]

+ Response 204 (text/plain)

### Remove dir for TAR archive testing as #User [POST]

+ Request (application/json)
        [
            "/www/test_archives/tar"
        ]

+ Response 204 (text/plain)
