# Group Remove Test environment
Remove test environment.

## Remove dirs for ZIP archive testing as Root [POST /api/filemanager/del]

+ Request (application/json)
        [
            "/var/www/test_archives/zip"
        ]

+ Response 204 (text/plain)

## Remove dirs for TAR archive testing as Root [POST /api/filemanager/del]

+ Request (application/json)
        [
            "/var/www/test_archives/tar"
        ]

+ Response 204 (text/plain)

## Remove dir for TAR archive testing as #User [POST /api/filemanager/del]

+ Request (application/json)
        [
            "/www/test_archives/tar"
        ]

+ Response 204 (text/plain)

