# Group Remove Test environment
Remove test environment.

## Remove MySQL test user as #User [POST /api/mysql/users/del]

Remove test user.

+ Request (application/json)
        {  
            "Username":"DBUser1"
        }

+ Response 204 (text/plain)

## Remove PgSQL test user as #User [POST /api/pgsql/users/del]

Remove test user.

+ Request (application/json)
        {  
            "Username":"DbTester"
        }

+ Response 204 (text/plain)

## Remove dirs for ZIP archive testing as Root [POST /api/filemanager/del]


+ Request (application/json)
        [
            "/var/www/test_archives/zip"
        ]

+ Response 204 (text/plain)

## Remove dir for TAR archive testing as #User [POST /api/filemanager/del]


+ Request (application/json)
        [
            "/www/test_archives/tar"
        ]

+ Response 204 (text/plain)
