# Group Create Test environment
Creating test environment.

## Add MySQL test user as #User [POST /api/mysql/users/set]
Add test user for PgSQL dumps.

+ Request (application/json)
        {  
        "Username":"DBUser1",
        "Password":"NewMyDBUserPassword",
        "Host":"localhost"
        }

+ Response 204 (text/plain)

## Add PgSQL test user as #User [POST /api/pgsql/users/set]
Add test user for PgSQL dumps.

+ Request (application/json)
        {  
            "Username":"DbTester",
            "Password":"NewMyDBTesterPassword"
        }

+ Response 204 (text/plain)

## Add Import PGSQL db [POST /api/pgsql/db/set]

+ Request (application/json)
        {  
            "DbName":"DbImport",
            "DbUser":"DbTester"
        }

+ Response 204 (text/plain)

## Create test.html file by Root [POST /api/filemanager/editfile]
Create /var/www/test.html by Root.

+ Request (application/json)
        {
            "Filename": "/var/www/test.html",
            "Encoding": "ISO 8859-2",
            "Text":"<h1>Hello world!</h1>"
        }

+ Response 204 (text/plain)

## Create /test.html file by #User [POST /api/filemanager/editfile]
Create /home/USER/test.html by User.

+ Request (application/json)
        {
            "Filename": "/test.html",
            "Encoding": "ISO 8859-2",
            "Text":"<h1>Hello world!</h1>"
        }

+ Response 204 (text/plain)

## Create from_root.html in user's dir by Root [POST /api/filemanager/editfile]

+ Request (application/json)
        {
            "Filename": "/home/regularUser/from_root.html",
            "Encoding": "ISO 8859-2",
            "Text":"<h3>Created by root!</h3>"
        }

+ Response 204 (text/plain)

## Create dirs for TAR archive testing as Root [POST /api/filemanager/mkdir]

+ Request (application/json)
        {
            "Dir":   "/var/www",
            "Mkdir": "test_archives/tar"
        }

+ Response 204 (text/plain)

## Create dirs for ZIP archive testing as Root [POST /api/filemanager/mkdir]

+ Request (application/json)
        {
            "Dir":   "/var/www",
            "Mkdir": "test_archives/zip"
        }

+ Response 204 (text/plain)

## Create dir for TAR archive testing as #User [POST /api/filemanager/mkdir]

+ Request (application/json)
        {
            "Dir":   "/www",
            "Mkdir": "test_archives/tar"
        }

+ Response 204 (text/plain)

## Add test.com domain as #User [POST /api/webdomains/set]

+ Request (application/json)
        {  
                "Domain":"test.com",
                "Alias":"www.test.com site.test.com",
                "Ip":"$SERVER_IP",
                "IndexFile":"index.html",
                "Encoding":"utf8",
                "Subdomains":true,
                "PHP":true,
                "DNS":true,
                "SSL":false,
                "Analytics":true
        }

+ Response 204 (text/plain)
