# Group Remove testing user regularUser

## #AuthRoot for testing user removing [POST /login]

+ Request (application/json)
        {
            "Login": "root",
            "Password": "$ROOT_PASSWORD"
        }

+ Response 200 (application/json)
        {
            "Auth": "Logged",
            "Theme": "Simple",
            "Language": "EN"
        }


## Removing testing user regularUser [POST /api/users/del]

+ Request (application/json)
        {  
            "Name":"$USER_NAME"
        }

+ Response 204 (text/plain)


## Remove Slack Plugin [POST /api/plugins/del]

Remove plugin from system

+ Request (application/json)
        [ "slack" ]

+ Response 204 (text/plain)


## Remove PhpMyAdmin Plugin [POST /api/plugins/del]

Remove plugin from system

+ Request (application/json)
        [ "pmainstaller" ]

+ Response 204 (text/plain)


## Logout from Root [GET /logout]

+ Response 204 (text/plain)
