## Add or Edit Email box [/api/email/set]

Add new or edit existent email box.

+ Attributes
  + Email (required, string) - Email box name.
  + Alias (required, string) - Box aliases.
  + Size (required, number) - Box size limit in megabytes. Zero is unlimited.
  + Password (required, string) - Password of the box.
  + Username (optional, string) - Owner of the box. Only `root` can set this parameter.

### Add or edit Email box [POST]

+ Request (application/json)
    {  
       "Email":"test@$TESTING_DOMAIN",
       "Alias":"kmsddf@mail.ru",
       "Size":123,
       "Password":"bc861g23d"
    }

+ Response 204 (text/plain)

## List Email boxes [/api/email/list]

List all email boxes.

### List email boxes[GET]

+ Response 200 (application/json)
    [  
       {  
          "Email":"test@$TESTING_DOMAIN",
          "Size":123,
          "Alias":"kms@mail.ru"
       }
    ]

## @Hook pop3/smtp testing [/api/email]
Pop3 and SMTP testing by python script.

### @Hook pop3/smtp testing [GET]

+ Response 202


## Remove Email boxes [/api/email/del]

Remove Email box.

### Remove Email box [POST]

+ Request (application/json)
    ["test@$TESTING_DOMAIN"]

+ Response 204 (text/plain)

### Remove non existent emailbox #Error [POST]

+ Request (application/json)
    ["testNotExistent@$TESTING_DOMAIN"]

+ Response
