## Search for packages [POST /api/syspackages/search]

Searches for packages in apt or yum.

+ Request (application/json)

        {
            "Package":"nano"
        }

+ Response 200 (application/json)
        [
            {
                "Name":        "httpd",
                "Description": "Apache httpd server",
                "Version":     "2.0.1",
                "Repo":        ""
            }
        ]

## Install packages [POST /api/syspackages/install]

Installing packages by apt or yum.

+ Request (application/json)

        ["nano","mc"]

+ Response 204 (text/plain)

        
## List packages [POST /api/syspackages/list]

List installed system packages.

+ Response 200 (application/json)
          [
            {
                "Name":        "httpd-2.0.2",
                "Description": "This is apache web server",
                "Version":     "2.0.2",
                "Repo":        "epel"
            }
          ]

## Remove packages [POST /api/syspackages/remove]

Remove installed packages by apt or yum.

+ Request (application/json)

        ["nano","mc"]

+ Response 204 (text/plain)