# SHM v1 API
FORMAT: 1A

# Group Panel Authorization

First of all you must login into panel as a user.
For login you must use your credentials of user or root login and password if you are the server administrator.

## User login [/login]

If login and password is correct you will recieve success login response.
`Theme`  is GUI theme for using after logged. `Language` is a user defined interface language.

+ Attributes
    + Login (required,string) - User's login, which is email or root for admin.
    + Password (required,string) - User defined password or root password for admin.
    + Auth (string) - Authorization status.

### Login success [POST]
If login and password is correct you will recieve success login response.
`Theme`  is GUI theme for using after logged. `Language` is a user defined interface language.

+ Attributes
    + Theme:Simple (string) - User defined GUI theme.
    + Language:EN (string) - User defined language for GUI.

+ Request Login Success (application/json)

        {
        "Login": "root",
        "Password": "goodPassword"
        }

+ Response 200 (application/json)

        {
        "Auth": "Logged",
        "Theme": "Simple",
        "Language": "EN"
        }

### Login fails [POST]
If login and password is not correct you will recieve 403. 
Debug informaion about user not found or wrong password are in the system's log file.

+ Request Login Fails (application/json)

        {
        "Login": "root",
        "Password": "wrongPassword"
        }

+ Response 403 (application/json)

        {
         "Auth": "Denied"
        }

### HOTP code required [POST]
If user turned on two step authorization by code from Google Authnticator or other HOTP compatible app, 
HOTP code must be present with login and password fields.


+ Attributes
    + HOTP (number) - Code from device for two step authorization.

+ Request Login Fails (application/json)

        {
        "Login": "hotpUser",
        "Password": "goodPassword"
        }

+ Response 449 (application/json)

        {
         "Auth": "HOTP required"
        }
 
### Login with HOTP success [POST]

+ Request Login Success (application/json)

        {
        "Login": "root",
        "Password": "goodPassword",
        "HOTP":12345
        }

+ Response 200 (application/json)

        {
        "Auth": "Logged",
        "Theme": "Simple",
        "Language": "EN"
        }


### Login fails because HOTP wrong code [POST]

+ Request Login Fails (application/json)

        {
        "Login": "root",
        "Password": "goodPassword",
        "HOTP":54321
        }

+ Response 403 (application/json)

        {
         "Auth": "HOTP wrong code"
        }