#!/bin/bash

# Remove comments '#' and empty lines from Apiary.Manifest.$EXT file
# for proper apiary.io documentation and concat it to one big apib file
# Example of using: ./MakeManifest.sh all ./apiary.apib

APIB_FILE=$2

rm -f $APIB_FILE

echo "Start $APIB_FILE creation from apiary.manifest.$1 list."

FILES=`grep -v "#" apiary.manifest.$1 | grep -v -e '^$'`
while read -r line; do
    echo "$line processed"
    # Concat file
    for i in $line
    do
        cat $i >> $APIB_FILE
        # Append 3 lines
        echo -e "\n\n\n" >> $APIB_FILE
    done

    # Catch error
    if [ $? -ne 0 ]; then
        echo "Error during creating apib file"
        exit 1;
    fi
done <<< "$FILES"

chmod 777 $APIB_FILE

echo "Done."
