# Data Structures

## Error (object)
+ error (required,object)

## Files (object)
+ Dir (required, boolean) - Is dir.
+ Name (required, string) - Name of the dir or file.
+ Size (required, number) - Size in bytes.
+ Permissions (required, number) - Permissions.
+ Owner (required, string) - Owner of file or dir.
+ Group (required, string) - Group of file or dir.
+ Modified (required, string) - Date time of last modification.
