## Start ClamAV scan [POST /api/clamav/scan]
Start ClamAV scanner and send user message after scan finish.

+ Request (application/json)
        {  
            "Dir":"/var"
        }
        
+ Response 204 (text/plain)
