## Add or Edit FTP account [/api/pftpd/set]

Add or edit FTP accounts.

+ Attributes
	+ UserID (required, string) - FTP account login name.
	+ Password (required, string) - FTP account password.
	+ User (optional, string) - Panel user which owns FTP account. Only `root` can set User.
	+ Homedir (required, string) - FTP directory path related to current user's homedir.

### Add or edit FTP [POST]

+ Request (application/json)
		{
        "UserID":     "FTP1",
        "Password" : "FTPPassword",
        "Homedir":       "ftpdir"
        }

+ Response 204 (text/plain)

## List FTP accounts [/api/pftpd/list]

List all user's FTP account.

### List all databases [GET]

+ Response 200 (application/json)
		[
		{  
		   "UserID":"RegularUser_FTP1",
           "Homedir":  "/ftpdir"
        }
        ]

## Remove FTP accounts [/api/pftpd/del]

Remove FTP accounts.

### Remove ftp account [POST]

+ Request (application/json)
		["FTP1"]

+ Response 204 (text/plain)

### Remove non existent ftp account [POST]

+ Request (application/json)
		["FTPNotExist"]

+ Response 500 (application/json)
		{
		}
