# Group Logout

To close current session user can logout by request. This is not necessary but recommended to close the session.
If user is inactive for 1800 seconds, session will be destroyed by the panel itself. 
You can change this value in config file at `GHttp.SessionLifeTime`.

## #User logout [GET /logout]
Close the regular user session.

+ Response 204 (text/plain)

## Root logout [GET /logout]
Administrator `root` session close.

+ Response 204 (text/plain)
