# Group Panel Authorization

First of all you must login into panel as `root` to gain administrator privileges or as a regular user.
For login you must use your credentials of user or root login and password if you are the server administrator.

+ Attributes
    + Login (required,string) - User's login, which is email or root for admin.
    + Password (required,string) - User defined password or root password for admin.
    + Hotp (optional, string) - Code from two step authorization app.
    + Auth (string) - Authorization status.