# Two step authorization
For using two step authorization you can install **Google Authenticator** or other mobile app that support HOTP protocol.
There are two ways to add your app for two step authorization:
* Scan generated QR code on your mobile Google Authenticator app,
* Enter generated code at your mobile Google Authenticator app.


## Generate code for Google Authenticator [/hotp/generate]
This request will generate one time code that you need to save in your Google Authenticator app.

+ Attributes
    + Login (required,string) - User's login, which is email or root for admin.
    + Password (required,string) - User defined password or root password for admin.
    + Auth (string) - Authorization status.


### Login success [POST]
If login and(or) password is correct you will receive success login response with
`Theme` is a GUI theme, `Language` is a user defined interface language.
Login script do redirect to `https://server:port/Theme` to load GUI for theme.


+ Attributes
    + Theme:Simple (string) - User defined GUI theme.
    + Language:EN (string) - User defined language for GUI.

+ Request Login Success (application/json)
        {
            "Login": "root",
            "Password": "goodSHMpassword"
        }

+ Response 200 (application/json)
        {
            "Auth": "Logged",
            "Theme": "Simple",
            "Language": "EN"
        }