### HOTP code required [POST]

How to [turn on two step authorization](two-step-authorization)
If user turned on two step authorization from Google Authenticator or other HOTP compatible mobile app, 
HOTP code must be present along with login and password fields.
You need to repeat login request with HOTP code from user's mobile app.

+ Request (application/json)
        {
            "Login": "hotpUser",
            "Password": "hotpUserSecretPassword"
        }

+ Response 449 (application/json)
        {
            "Auth": "HOTP required"
        }
 
### Login with HOTP success [POST]

If HOTP code from user's app correct, you'll receive `200` and `Login success` reply.

+ Attributes
    + HOTP (required, string) - Code from device for two step authorization.

+ Request (application/json)
        {
            "Login": "hotpUser",
            "Password": "hotpUserSecretPassword",
            "Hotp":"12345"
        }

+ Response 200 (application/json)
        {
            "Auth": "Logged",
            "Theme": "Simple",
            "Language": "EN"
        }


### Login fails because HOTP wrong code [POST]
In case of wrong HOTP code `403` would be received. 
You can send another request with correct HOTP code.

+ Request (application/json)
        {
            "Login": "hotpUser",
            "Password": "hotpUserSecretPassword",
            "Hotp":"54321"
        }

+ Response 403 (application/json)
        {
            "Auth": "HOTP wrong code"
        }