## Two step authorization [/hotp/{action}]

For using two step authorization you can install **Google Authenticator** or other mobile app that support HOTP protocol.
There are two ways to add your app for two step authorization:
* Scan generated QR code on your mobile Google Authenticator app,
* Enter generated code at your mobile Google Authenticator app.

+ Parameters
    + action (string) - qr, code, check, toggle actions.

This request will generate one time code that you need to save in your Google Authenticator app.


### Generate QR code [POST]
Generated QR code you can scan by Google Authenticator to add account.


+ Request Login Success (application/json)
        {
            "Login": "root",
            "Password": "goodSHMpassword"
        }

+ Response 200 (application/json)
        {
            "Auth": "Logged",
            "Theme": "Simple",
            "Language": "EN"
        }