## Root login [/login]
For login you must use your root system password and login `root`.

### Root login fails [POST]
If password is not correct you will receive `403 Forbidden`. 

+ Request (application/json)
        {
        "Login": "root",
        "Password": "wrongPassword"
        }

+ Response 403 (application/json)
        {
            "Auth": "Denied"
        }

### Root login success #AuthRoot [POST]

+ Attributes
    + Theme:Simple (required, string) - User defined GUI theme.
    + Language:EN (required, string) - User defined language for GUI.

+ Request (application/json)
        {
            "Login": "root",
            "Password": "goodSHMpassword"
        }

+ Response 200 (application/json)
        {
            "Auth": "Logged",
            "Theme": "Simple",
            "Language": "EN"
        }