## List all Plugins from repository [GET /api/plugins/list]

List all plugins from repository.

+ Response 200 (application/json)
        [
            {
                "Installed": true,
                "Name": "slack",
                "Version": "1.0.1b",
                "Author": {
                    "Name": "Pavlo Zibrow",
                    "Url": "https://slack.com"
                    },
                "Description": "Slack server messages notification",
                "Urls": [
                    "http://9521.geeks.team/slack.tar.gz"
                    ],
                "Tasks": {},
                "Triggers": {}
            }
        ]
