## List all Plugins from repository [GET /api/plugins/list]
List all plugins from repository.

+ Response 200 (application/json)
        [
            {
                "Installed": true,
                "Name": "slack",
                "Version": "1.0.1b",
                "Author": {
                    "Name": "Pavlo Zibrow",
                    "Url": "https://slack.com"
                    },
                "Description": "Slack server messages notification",
                "Urls": [
                    "http://9521.geeks.team/slack.tar.gz"
                    ],
                "Tasks": {},
                "Triggers": {}
            }
        ]

## Start Plugin task #Error [GET /api/plugins/task?plugin=slack&bin=nonexistentbin]
Start non existent plugin programm from /bin directory as a background task.


## Remove Nonexistent Plugin #Error [POST /api/plugins/del]
Remove non existent plugin from system

+ Request (application/json)
        [ "NonExistentPlugin" ]

+ Response

## Call Nonexistent Plugin bin #Error [GET /api/plugins/call?plugin=dummy&bin=nonexist]
Call non existent bin

