## Setting Cron Jobs [POST /api/cron/set]

Remove all cron jobs for user and sets them from request.

+ Request (application/json)

        [
            {
                "User": "nobody",
                "Mail": "test@localhost",
                "Jobs":{
                    "* * * * *":"echo 'Go!'>/tmp/cron_test"
                }
            }
        ]

+ Response 204 (plain/text)

## Setting Wrong Cron Job [POST /api/cron/set]

Setting cron job with wrong parameters.

+ Request (application/json)

        [
            {
                "User": "nobody",
                "Mail": "test@localhost",
                "Jobs":{
                    "@nosuchday":"echo 'Go!'>/tmp/cron_test"
                }
            },
            {
                "User": "root",
                "Mail": "test@localhost",
                "Jobs": {
                    "* * *":"echo 'Go!'>/tmp/cron_test"
                }
            }
        ]

+ Response 500 (application/json)
    + Attributes (Error)
       
## List all cron jobs [GET /api/cron/list]

Lists all cron jobs for all users.

+ Attributes
  + User (required, string) - Owner of the cron job.
  + Mail (required, array) - Mail for job messages.
  + Jobs (optional, object) - Cron jobs.

+ Response 200 (application/json)
        [
            {
                "User": "nobody",
                "Mail": "test@localhost",
                "Jobs": {
                    "* * * * *":"echo 'Go!'>/tmp/cron_test"
                }
            }
        ]
