## Install LetsEncrypt plugin [POST /api/plugins/install]
Install plugin from repository

+ Request (application/json)

        {
            "Plugin":"letsencrypt"
        }

+ Response 204 (text/plain)


## Remove LetsEncrypt Plugin [POST /api/plugins/del]
Remove plugin from system

+ Request (application/json)

        [ "letsencrypt" ]

+ Response 204 (text/plain)
