# Group MySQL Users

Panel users can have their own database users and databases.
Database can be on local host and remote. Database connection can be configured by `Mysql.Host`, `Mysql.Port`, `Mysql.User` (Root or admin database user), `Mysql.Password` (Password for root or database admin) section at main config file.