## Domains list [/api/info/domains]

In many cases GUI need to get list of user's domains. For example for email box add or so on. 
Root user and regular user have different reply, because root will get all domains for all users and user will get only its own.

### Root domains list [GET]
Root get all domains and they ownerd

+ Response 200 (application/json)
        {
        "test.com": "$USER_NAME"
        }

### Domains list for #User [GET]

+ Response 200 (application/json)
        [
        "test.com"
        ]


