### Root user [GET]

Root user as administrator have different session information.
Administrator will get information about server status and resources usage to show those information at admin's gui dashboard.

+ Attributes
    + Build (required,string) - API server build datetime.
    + Users (required, array) - All Usernames existing in a panel.
    + Templates (required, array) - All User privileges templates.
    + ActiveSessions (required, number) - Total active users sessions for now.
    + Stats.Diskspace (required, number) - Disk space usage in percents.
    + Stats.DBs (required, number) - Total Databases (MySQL, PgSQL and etc.) owned by users.
    + Stats.DBUsers (required, number) - Total Databases Users (MySQL, PgSQL and etc.) owned by users.
    + Stats.FTPs (required, number) - Total FTP accounts owned by users.
    + Stats.WebDomains (required, number) - Total webdomains owned by users.
    + Stats.DNSDomains (required, number) - Total domains in DNS server owned by users.
    + Stats.Emails (required, number) - Total email accounts owned by users.

+ Response 200 (application/json)
        {
        "Build":"01.12.2016 Date",
        "Users": ["UserOne","UserTwo"],
        "Templates": ["SimpleUser","BigBoss"],
        "ActiveSessions":10,
        "Stats":
            {
            "Diskspace": 50,
            "Traffic": 0,
            "DBs":12,
            "DBUsers":24,
            "FTPs":5,
            "WebDomains":4,
            "DNSDomains":4,
            "Emails":54
            }
        }
