## Exim mail delivery log [/api/eximlog/delivery]

Mail delivery log.

### Show total mail delivery log [GET]
Show total mail delivery count.

+ Response 200 (application/json)
        {  
            "Count":8274
        }
        
### Show mail delivery by date [POST]
Show mail delivery log by date.

+ Request (application/json)
        {  
            "Date":"04.04.2016"
        }

+ Response 200 (application/json)
        [  
            {  
                "ID":"sjdfgb923uy4ybsffd",
                "DateTime":"2015-09-09 12:12:12",
                "From":"dsfdf@ad.com",
                "To":"tt@gmail.com",
                "User":"nik1",
                "Size":123,
                "Status":"Delivered",
                "Additional":""
            }
        ]


### Show mail delivery log by email [POST]
To find some email in a delivery log.

+ Request (application/json)
        {  
            "Email":"example@example.com",
            "Date":"04.04.2016"
        }

+ Response 200 (application/json)
        [  
            {  
                "ID":"sjdfgb923uy4ybsffd",
                "DateTime":"2015-09-09 12:12:12",
                "From":"dsfdf@ad.com",
                "To":"tt@gmail.com",
                "User":"nik1",
                "Size":123,
                "Status":"Delivered",
                "Additional":""
            }
        ]
