## Get nginx status [GET /api/nginx/status]
Getting nginx status information page.

+ Response 200 (application/json)
            {  
            "hostname":"vds",
            "server_version":"1.8.0",
            "basic_status":{  
                "active_connections":1,
                "server_accepts":2,
                "handled":2,
                "requests":2,
                "reading":0,
                "writing":1,
                "waiting":0
            },
            "requests":[  
                    {  
                        "client":"45.78.13.21",
                        "vhost":"93.58.28.25",
                        "request":"GET /handler HTTP/1.1",
                        "mode":"W",
                        "status":200
                    }
                ]
            }
