## Import dump to mysql database #User [POST /api/mysql/db/import]

+ Request (application/json)

        {
                "Filepath": "/www/mysql.sql",
                "Db": "MysqlOne"
        }

+ Response 204 (text/plain)
