## Restore backup by #User [POST /api/ubackup/restore]

+ Request (application/json)
        {
            "Archive":"latestBackup",
            "IP":"$SERVER_IP",
            "MySQLUser":"NewMySQL1",
            "PgSQLUser":"NewPgSQL1"
        }

+ Response 204 (text/plain)
