## Restore backup [POST /api/ubackup/restore]
Restore user backup. During restore users data may be overwriten.
Restore user backup can be done only logged as user account.

+ Request (application/json)
        {
            "Archive":"latestBackup.tar.gz",
            "IP":"$SERVER_IP",
            "MySQLUser":"NewMySQL1",
            "PgSQLUser":"NewPgSQL1",
        }

+ Response 204 (text/plain)
