# Group User privileges templates

Every user in the panel has it own priveleges. Priveleges prevent unrestricted access to modules.
Using privileges prevent dedublicating same restrictions to users.
