## Download files [/api/filemanager/download]

Download file from filesystem. Users can download only files from they homedir.

### Download file [POST]

+ Request (application/json)
        {
            "Filename": "/etc/passwd"
        }

+ Response 200 (application/octet-stream)
    + Headers
        Content-Disposition: "attachment; filename=passwd"
    + Body
            
            

### Download file by #User [POST]

+ Request (application/json)
        {
            "Filename": "/test.jpg"
        }

+ Response 200 (application/octet-stream)
    + Headers
        Content-Disposition: "attachment; filename=test.jpg"
        content-length: 13263
    + Body
            
            
        
### Download file #Error by #User [POST]

+ Request (application/json)
        {
            "Filename": "/../../../../etc/passwd"
        }

+ Response
