## Edit text file [/api/filemanager/editfile]
Users can edit text file content.

### Edit text file by Root [POST]

+ Request (application/json)
        {
            "Filename": "/var/www/test.html",
            "Encoding": "ISO 8859-2",
            "Text":"<h2>Root was here!</h2>"
        }
        
+ Response 204 (text/plain)

### Edit text file by #User [POST]
User can edit only owned files in his homedir.

+ Request (application/json)
        {
            "Filename": "/test.html",
            "Encoding": "ISO 8859-2",
            "Text":"<h2>RegularUser was here!</h2>"
        }
        
+ Response 204 (text/plain)

### Edit text file #Error by #User [POST]

+ Request (application/json)
        {
            "Filename": "/from_root.html",
            "Encoding": "ISO 8859-2",
            "Text":"Edit by regular User"
        }
        
+ Response 
