## List directory [/api/filemanager/list]

Root can list all directories on server.
User can list only directories under his homedir.

### List dir by Root [POST]

+ Request (application/json)
        {
            "Dir": "/var/www"
        }

+ Response 200 (application/json)
    + Attributes (array[Files])

### List dir by User [POST]

+ Request (application/json)
        {
            "Dir": "/www"
        }

+ Response 200 (application/json)
    + Attributes (array[Files])

### List dir Error by User [POST]

+ Request (application/json)
        {
            "Dir": "/../../www/no_such_dir"
        }

+ Response 500 (application/json)
    + Attributes (Error)
    