## Change permissions [/api/filemanager/set]

Root can change any files.
User can change only files within his homedirectory. Owner for modified files will be a current user.

### Change permissions by Root [POST]

+ Request (application/json)
        {
            "Path":  "/var/www/test.html",
            "Mode":  777,
            "Owner": 99,
            "Group": 3,
            "Recursive":true
        }

+ Response 204 (text/plain)


### Change permissions by #User [POST]

User can't change owner of the files, only permissions.

+ Request (application/json)
        {
            "Path":  "/test.html",
            "Mode":  777,
            "Recursive":true
        }

+ Response 204 (text/plain)


### Change permissions #Error by #User [POST]
User can't change files which not owned.

+ Request (application/json)
         {
            "Path":  "/from_root.html",
            "Mode":  777
        }

+ Response


### Change permissions #Error while file Not Exist by #User [POST]
User can't change files which not owned.

+ Request (application/json)
         {
            "Path":  "/dir_which/not_exist.txt",
            "Mode":  777
        }

+ Response
 