## Set user password [/api/users/password]

You can change users password for panel and ssh access. `root` can change password for all users, regular users can change only own password.

+ Attributes
    + Name (required,string) - User name.
    + Password (optional,string) - New password.

### Success [POST]

+ Request (application/json)
        {  
            "Name":"Tester",
            "Password":"NewVerySecretTesterPassword"
        }

+ Response 204 (text/plain)
