## Get users list [/api/users/list]

Return all users exists in panel and information.

### Success [GET]

+ Response 200 (application/json)
    [
            {
            "Username":"Tester",
            "Info":
                {
                "Active":false,
                "Created":"Tue Nov 17 00:00:00 EET 2015",
                "Comment":"Just a testing user",
                "Template":"SuperAdmin",
                "Email":"root@localhost",
                "Theme":"Simple",
                "Language":"EN",
                "HOTP":
                    {
                    "Active":false
                    }
                },
            "Limits":{},
            "Stats":{}
            }
        ]
