# Group Users

Users can login to panel, have their own domains, databases, limited disk space, and etc.
Users in panel are system users too. They can have or haven't SSH access. Each user has its own privileges. 
For managing users privileges in panel we have such thing as "User Limits Templates". There is a templates with list of limits which can apply to one or more users. More information are in "User Templates" section.

Only user with login `root` or user with priveleges template named `SuperAdmin` can add, edit or remove users!