## Disable, enable users [/api/users/toggleactive]

Inactive users can not login into panel, webdomains are disabled too.
This request toggle user status from active to disabled or vice versa.

+ Attributes
    + Name (required,string) - Login name.

### Success [POST]

+ Request (application/json)
        {  
            "Name":"Tester"
        }

+ Response 200 (text/plain)
