## Disable, enable users [/api/users/password]

Inactive users can not login into panel, webdomains are disabled too.
This request toggle user status from active to disabled or vice versa.

+ Attributes
    + Name (required,string) - Login name.

### Success [POST]

+ Response 200 (application/json)
	{
	
	}