## Getting System usage chart [GET /api/watchdog/chart]

+ Request (application/json)
            {  
                "Get":"SysStat",
                "Date":{  
                    "From":"$DATE_YMD 10:15",
                    "To":"$DATE_YMD 17:55",
                    "EntriesCount":24
                }
            }

+ Response 200 (application/json)
            {  
                "labels":[],
                "datasets":[
                    {  
                        "label":"CPU",
                        "data":[]
                    },
                    {  
                        "label":"RAM",
                        "data":[]
                    },
                    {  
                        "label":"SWAP",
                        "data":[]
                    },
                    {  
                        "label":"HDD",
                        "data":[]
                    },
                    {  
                        "label":"WA",
                        "data":[]
                    }
                ]
            }

## Getting Network usage chart [GET /api/watchdog/chart]

+ Request (application/json)
            {  
                "Get":"NetStat",
                "Date":{  
                    "From":"$DATE_YMD 10:15",
                    "To":"$DATE_YMD 17:55",
                    "EntriesCount":24
                }
            }

+ Response 200 (application/json)
            {  
                "labels":[],
                "datasets":[
                    {  
                        "label":"InMbitps",
                        "data":[]
                    },
                    {  
                        "label":"InPps",
                        "data":[]
                    },
                    {  
                        "label":"OutMbitps",
                        "data":[]
                    },
                    {  
                        "label":"OutPps",
                        "data":[]
                    }
                ]
            }

## Getting Traffic usage chart [GET /api/watchdog/chart]

+ Request (application/json)
            {  
                "Get":"Traffic",
                "Interface":"venet0",
                "Date":{  
                    "From":"$DATE_YMD 10:15",
                    "To":"$DATE_YMD 17:55",
                    "EntriesCount":24
                }
            }

+ Response 200 (application/json)
            {  
            "labels":[],
            "datasets":[  
                    {  
                        "label":"In",
                        "data":[]
                    },
                    {  
                        "label":"Out",
                        "data":[]
                    }
                ]
            }
