## MySQL Add or Edit Databases [/api/mysql/db/set]

Add or edit database for database user.

+ Attributes
	+ DbName (required, string) - Database name.
	+ DbUsers (required, array) - Database users owners.
	+ Host:localhost (optional, string) - Hostname  from which user can login to database.
	+ Privileges (optional, object) - Database priveleges for user.

### Add or edit database [POST]

+ Request (application/json)
        {  
		   "DbName":"DbOne",
		   "DbUsers":[ 
		   		{
	   			"DBUser1": {
	   				"Delete_priv":true
	   				}
				}
		   	],
		   "Host":"localhost"
		}

+ Response 204 (text/plain)

## MySQL List Databases [/api/mysql/db/list]

List all panel user databases.

### List all databases [GET]

+ Response 200 (application/json)
		[  
		   {  
		      "DbName":"DBOne",
		      "DbUsers":[ 
			   		{
		   			"DBUser1": {
		   				"Delete_priv":true
		   				}
					}
		   		],
		      "Size":999,
		      "Tables":111,
		      "Host":"localhost"
		   }
		]
## MySQL Delete Databases [/api/mysql/db/del]

Remove databases listed in request.

### Remove databases [POST]

+ Request (application/json)
        [  
		   "DbOne"
		]

+ Response 204 (text/plain)
