## Export MySQL database [/api/mysql/db/export]

Dump MySQL databse and send it.

+ Attributes
	+ Database (required, string) - Database name to dump.

### Export database [POST]

+ Request (application/json)
        {  
		   "Dbname":"DbExport"
		}

+ Response 200 (text/plain)
	+ Headers
		content-disposition: attachment;
