## Modifying MySQL users [POST /api/mysql/users/set]

Add or edit database user if username already exist.

+ Attributes
  + Username (required, string) - Database username. Prefix must be panel user name, and append in GUI before request.
  + Password (required, string) - Database user password.
  + Host:localhost (optional, string) - Hostname  from which user can login to database.

+ Request (application/json)

        {  
           "Username":"DBU",
           "Password":"NewMyDBPassword",
           "Host":"localhost"
        }

+ Response 204 (text/plain)

## Get all MySQL users  [GET /api/mysql/users/list]

List all database users of current session panel user.

+ Attributes
  + DBs (required, number) - Number of user's databases. 

+ Response 200 (application/json)

        [  
           {  
              "Username":"Testuser_DBU",
              "Host":"localhost",
              "DBs":0
           }
        ]

## Removing MySQL users [POST /api/mysql/users/del]

Removing MySQL user and all him databases. If `ReplaceBy` parameter, databases not be deleted, they transfered to DB username in request instead.

+ Attributes
  + ReplaceBy (required, string) - Database username to transfer all databases from removing database user.

+ Request (application/json)

        {  
        "Username":"DBU"
        }

+ Response 204 (text/plain)
