## PgSQL Add or Edit Databases [/api/pgsql/db/set]

Add or edit database for database user.

+ Attributes
	+ DbName (required, string) - Database name.
	+ DbUser (required, string) - Database user owner for new database.

### Add or edit database [POST]

+ Request (application/json)
        {  
		   "DbName":"DbOne",
		   "DbUser":"DbTester"
		}

+ Response 204 (text/plain)

## PgSQL List Databases [/api/pgsql/db/list]

List all panel user databases.

### List all databases [GET]

+ Response 200 (application/json)
		[  
		   {  
		      "DbName":"DBOne",
		      "DbUser":"RegularUser_DBUser1",
		      "Size":999,
		      "Tables":111
		   }
		]
## PgSQL Delete Databases [/api/pgsql/db/del]

Remove databases which names in the list of request.

### Remove databases [POST]

+ Request (application/json)
        [  
		   "DbOne"
		]

+ Response 204 (text/plain)
