## Export PgSQL database [/api/pgsql/db/export]

Dump PgSQL databse and send it.

+ Attributes
	+ Database (required, string) - Database name to dump.

### Export database [POST]

+ Request (application/json)
        {  
		   "Dbname":"DbOne"
		}

+ Response 200 (text/plain)
