## Export PgSQL database [/api/pgsql/db/export]

Dump PgSQL databse and send it.

+ Attributes
	+ Database (required, string) - Database name to dump.

### Export database [POST]

+ Request (application/json)
        {  
		   "Database":"DBOne",
		}

+ Response 200 (application/octet-stream)
	+ Body
        ---BOUNDARY
        Content-Disposition: attachment; name="DBOne.sql"
