## Search PECL packages [POST /api/php/peclsearch]

Searches for the mentioned pecl packages and output information about them.

+ Request (application/json)

        ["opcache","sqlite"]

+ Response 200 (application/json)
        [
            {
                "Name":        "opcache",
                "Version":     "0.9.1",
                "Description": "Zend OpCache cache"
            }
        ]

## Install PECL packages [POST /api/php/peclinstall]

Installing pecl packages.

+ Request (application/json)

        ["SQLite"]

+ Response 200 (application/json)
        {
            "Output":"text from console"
        }
        
## Remove PECL packages [POST /api/php/peclremove]

Removing pecl packages.

+ Request (application/json)

        ["ZendOpcache","SQLite"]

+ Response 200 (application/json)
        {
            "Output":"text from console"
        }
        