## Install Roundcube Plugin [POST /api/plugins/install]

Install Roundcube plugin from repository


+ Request (application/json)

        {
            "Plugin":"roundcube"
        }

+ Response 204 (text/plain)

## Add RoundCube WebMail to domain as #User [POST /api/webdomains/set]

Add Roundcube true to install Roundcube on domain.

+ Request (application/json)

         {  
            "Name":"$TESTING_DOMAIN",
            "Active":true,
            "Alias":"www.$TESTING_DOMAIN site.$TESTING_DOMAIN",
            "Ip":"$SERVER_IP",
            "IndexFile":"index.html index.php",
            "Encoding":"utf8",
            "Subdomains":true,
            "PHP":"fpm_nginx",
            "DNS":true,
            "SSL":false,
            "Analytics":true,

            "roundcube":true
        }

+ Response 204 (text/plain)

## !Hook test installation [HEAD /@hook]

Test installation by bot.

+ Response 299

## Remove RoundCube Plugin [POST /api/plugins/del]

Remove Roundcube plugin from system

+ Request (application/json)

        [ "roundcube" ]

+ Response 204 (text/plain)
