## Get current settings [GET /api/openssh/settings/get]

Get openssh server settings.

+ Response 200 (application/json)
        {
            "Port":                   22,
            "MaxAuthTries":           2,
            "PermitRootLogin":        true,
            "PasswordAuthentication": true,
            "AllowUsers":             ["usr1", "usr2"]
        }

## Set current settings [GET /api/openssh/settings/set]

Get openssh server settings.

+ Request (application/json)
        {
            "Port":                   22,
            "MaxAuthTries":           9,
            "PermitRootLogin":        true,
            "PasswordAuthentication": true,
            "AllowUsers":             ["root","shm_test_user"]
        }

+ Response 204 (text/plain)
