# Group Two step authorization

For using two step authorization you can install **Google Authenticator** or other mobile app that support HOTP protocol.
There are two ways to add your app for two step authorization:
* Enter generated code at your mobile Google Authenticator app,
* Scan generated QR code on your mobile Google Authenticator app,

For proper QR generation you need to get code first and only after that make request to generate QR.
