# Group Two step authorization

For using two step authorization you can install **Google Authenticator** or other mobile app that support HOTP protocol.
There are two ways to add your app for two step authorization:
* Scan generated QR code on your mobile Google Authenticator app,
* Enter generated code at your mobile Google Authenticator app.