## Generate QR [/hotp/qr]

This request will generate one time code that you need to save in your Google Authenticator app.

### Getting QR code image [POST]
Generated QR code you can scan by Google Authenticator to add account.

+ Response 200 (image/jpeg)