## Generate QR [/api/hotp/qr]

This request will generate one time code that you need to save in your Google Authenticator app.

### Getting QR image with code [GET]
Generate PNG image with QR code you can scan by Google Authenticator to add account.

+ Response 200 (image/jpeg)

## Generate code for enter by hand [/api/hotp/code]

This request will generate one time code that you need to enter while add new account to Google Authenticator app.

### Getting key code [GET]
Generate one time key code.

+ Attributes
    + Key (required,string) - One time generated key for app binding.

+ Response 200 (application/json)
        {
            "Key": "12368615794617"
        }

## Check for correct app binding [/api/hotp/check]

Before two step authorization cat be enabled we need to check if everything is good. 
You need to enter first generated code from your app.

### Code correct [POST]

+ Request Login Fails (application/json)
        {
            "Confirm": "95726283"
        }

+ Response 204 (text/plain)

### Wrong code [POST]
If app was not binded properly, first code was not accepted.

+ Request Login Fails (application/json)
        {
            "Confirm": "7324545"
        }

+ Response 406 (text/plain)

