## Upload file in temporary storage [/api/uploads/add]

Upload file in temporary storage, from which panel can operate file and move it to some location.

### Upload file [POST]
    + Request (multipart/form-data;boundary=---BOUNDARY)
        + Body
                ---BOUNDARY
                Content-Disposition: form-data; filename="Test.jpg"
                Content-Type: image/jpeg
                Content-Transfer-Encoding: base64

                /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAGPAc8DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZn

+ Response 204 (text/plain)

## List uploaded files [/api/uploads/list]

List all uploaded files of current user session.

+ Attributes
    + Filename (required, string) - Orignial filename.
    + TmpFilename (required, string) - Temporary filename to operate it by the panel.
    + Created (required,string) - Date time of file upload creation.

### List [GET]

+ Response 200 (application/json)
        [
            {
                "Filename":    "backup.sql",
                "TmpFilename": "max_h8762h",
                "Created":     "2015-09-12 12:45:32"
            }
        ]

## Delete all uploaded files [/api/uploads/clear]

Delete all temporary uploaded files by user.

### Clear [GET]

+ Response 204 (text/plain)
