## Upload file in temporary storage [/api/uploads/add]

Upload file in temporary storage, from which panel can operate file and move it to some location.

### Upload file [POST]
+ Request (multipart/form-data;boundary=---BOUNDARY)
    + Body

        ---BOUNDARY
        Content-Disposition: form-data; name="uploadfile"; filename="Test.jpg"
        Content-Transfer-Encoding: base64

        data

+ Response 204 (text/plain)

## List uploaded files [/api/uploads/list]

List all uploaded files of current user session.

+ Attributes
    + Filename (required, string) - Original filename.
    + TmpFilename (required, string) - Temporary filename to operate it by the panel.
    + Created (required,string) - Date time of file upload creation.

### List [GET]

+ Response 200 (application/json)
        [
            {
                "Filename":    "backup.sql",
                "TmpFilename": "max_h8762h",
                "Created":     "2015-09-12 12:45:32"
            }
        ]

## Delete all uploaded files [/api/uploads/clear]

Delete all temporary uploaded files by user.

### Clear [GET]

+ Response 204 (text/plain)
